### ISSUE TITLE
Totem is not showing in GNOME Software

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.gnome.Totem#2]
It looks like that Totem from Flathub is not showing in GNOME Software, but it can be found using `flatpak search` without any issues. Maybe some AppData-related issue?

**Comment by hadess** [comment]
I don't know why it would do that.

**Comment by TingPing** [comment]
At a glance it doesn't seem to be missing any info.

(I did find one minor issue though: https://gitlab.gnome.org/GNOME/totem/merge_requests/14)

**Comment by TingPing** [comment]
This *may* be relevant:

> The <compulsory_for_desktop> tag indicates that the component which the metadata belongs to is essential for the functionality of the defined desktop environment. Examples for compulsory components are the GNOME-Shell by the GNOME-Project, or the Plasma-Desktop by KDE, as well as things like iBus or the desktop login manager.  
>Software centers are expected to detect the running desktop environment and disable uninstallation for compulsory components of that desktop, so users will not be able to damage their currently running, primary desktop environment.

Don't know if that means it hides it entirely.

**Comment by DudleyDursley** [comment]
Gnome Software does find it, but only if you search for "Videos" and not for "Totem".

**Comment by AsciiWolf** [comment]
Oops, you're right!

**Comment by hadess** [comment]
> Maybe should be added as a keyword in the appstream file, but that is an issue for upstream.

appstream keywords are taken from the .desktop file for desktop applications:
https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#tag-ct-keywords
so this will be fixed by:
https://gitlab.gnome.org/GNOME/totem/merge_requests/87
