### ISSUE TITLE
The player gets stuck for indefinite time when subtitle is loaded

### ISSUE THREAD

**Issue by chakradhar-s** [flathub/org.gnome.Totem#32]
When subtitles are played for more than 6 times. The videos player v3.32.0 gets stuck for indefinite time.

**Comment by hadess** [comment]
This sounds like a bug in totem or GStreamer themselves. You'll need to file a bug at https://gitlab.gnome.org/GNOME/totem/issues/ with an explanation on how to reproduce the problem.

It might also be worth testing with the updated Totem 3.34.0 which should land later today.
