### ISSUE TITLE
The name org.freedesktop.Tracker1 was not provided by any .service files

### ISSUE THREAD

**Issue by HugLifeTiZ** [flathub/org.gnome.Totem#46]
I'm giving this a test on XFCE, and when I open the app without opening a file, it pops up a dialog complaining about a missing dbus service: "the name org.freedesktop.Tracker1 was not provided by any .service files"

It doesn't happen if I open a file with it, but it then does happen if I click the back button while viewing the file.

I'm presuming Tracker isn't part of XFCE and that's why that happens.

**Comment by hadess** [comment]
This is fixed in the latest version that was just merged, which has its own copy of Tracker in the sandbox. Should be in an update very soon (some time today).
