### ISSUE TITLE
Headers and example code in .Codecs extension

### ISSUE THREAD

**Issue by wjt** [flathub/org.gnome.Totem#54]
The `.Codecs` extension includes many headers in 'include/', and ffmpeg API usage examples in 'share/ffmpeg/examples'. This accounts for 1.5 MB of the 20 MB extension.

https://gist.github.com/wjt/355ba42cc519d0d4de8f6eb25ccfd940

I don't know whether `cleanup` runs before or after splitting into extensions but maybe just chucking these paths prefixed by `lib/codecs` into `cleanup` would do the job.

**Comment by hadess** [comment]
Saved about 4 megs:
https://github.com/flathub/org.gnome.Totem/pull/55
