### ISSUE TITLE
Confusing Description on Flathub Page

### ISSUE THREAD

**Issue by maymage** [flathub/org.gnome.Totem#86]
Hi, 

the **numbers** in the description on the flathub page are confusing. I cite

```
Changes in version 42.0

We are proud to announce Videos 3.34.0 as the latest stable version.

This new version...
```

Here it really isn't clear, what **3.34.0** means/stands for - I'd have expected **42.0** instead. 

Best

**Comment by hadess** [comment]
It's a copy/paste error when creating the release notes for version 42. I've fixed it upstream, and it should be updated on the website shortly.
