### ISSUE TITLE
Update app and runtime to 43.0

### ISSUE THREAD

**Issue by A6GibKm** [flathub/org.gnome.Totem#97]
As the title say the app needs an update to its latest version.

**Comment by hadess** [comment]
The work is being done here, if you want to help:
https://github.com/flathub/org.gnome.Totem.Devel/pull/6

**Comment by A6GibKm** [comment]
Gentle reminder to update the stable branch. Thanks!

**Comment by hadess** [comment]
There's still a crasher in Tracker that needs to be investigated with the newer libraries.

**Comment by hadess** [comment]
Hopefully https://github.com/flathub/org.gnome.Totem.Devel/pull/9 fixes it
